name: OIDC smoke test
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::330552995255:role/GitHubOIDC-EBDeploy
          aws-region: eu-north-1

      - name: Verify identity
        run: aws sts get-caller-identity
